-- Step 1: Truncate the existing brands table to clear all data
TRUNCATE TABLE public.brands CASCADE;

-- Step 2: Insert the new, clean data.
INSERT INTO public.brands (name, label)
VALUES
('365_organic', '365 Organic'),
('airchief_sun_pacific', 'Airchief (Sun Pacific)'),
('alderman_farms', 'Alderman Farms'),
('altar', 'Altar'),
('ambrosia_gold', 'Ambrosia Gold'),
('andy_boy', 'Andy Boy'),
('artisan_organics', 'Artisan Organics'),
('b_organic', 'B Organic'),
('baloian_farms', 'Baloian Farms'),
('big_chuy', 'Big Chuy'),
('big_y', 'Big Y'),
('boskovich_farms', 'Boskovich Farms'),
('brighthouse_organics', 'Brighthouse Organics'),
('cal_organic', 'Cal Organic'),
('capac_chief', 'Capac Chief'),
('chelan', 'Chelan'),
('church_brothers_farms', 'Church Brothers Farms'),
('cmi_orchards', 'CMI Orchards'),
('dandy', 'Dandy'),
('delano_farms', 'Delano Farms'),
('delcabo', 'delCabo'),
('dole', 'Dole'),
('driscolls', 'Driscolls'),
('durst_organic_growers', 'Durst Organic Growers'),
('east_coast_organics', 'East Coast Organics'),
('famous_vineyards', 'Famous Vineyards'),
('field___farm', 'Field & Farm'),
('foxy', 'Foxy'),
('fresh_express', 'Fresh Express'),
('freshire_farms', 'Freshire Farms'),
('full_circle_market', 'Full Circle Market'),
('good_and_gather', 'Good and Gather'),
('green_field_farms', 'Green Field Farms'),
('green_leaf', 'Green Leaf'),
('grow_true_organic', 'Grow True Organic'),
('hitchcock_farms', 'Hitchcock Farms'),
('josies_organics', 'Josie''s Organics'),
('joyfully_grown', 'Joyfully Grown'),
('juniper_hill_farm', 'Juniper Hill Farm'),
('kanzi', 'Kanzi'),
('kiku', 'Kiku'),
('lady_moon_farms', 'Lady Moon Farms'),
('lone_star_fresh', 'Lone Star Fresh'),
('marketside', 'Marketside'),
('masters_touch_organics', 'Masters touch organics'),
('mcclellan_organics', 'Mcclellan Organics'),
('mighty_minis', 'Mighty Minis'),
('moonlight', 'Moonlight'),
('nature_fresh_farms', 'Nature Fresh Farms'),
('natures_bounty', 'Nature''s Bounty'),
('natures_promise', 'Nature''s Promise'),
('natures_reward', 'Natures Reward'),
('new_sprout_organic_farms', 'New Sprout Organic Farms'),
('none', 'None'),
('north_bay_produce', 'North Bay Produce'),
('oak_canyon_farms', 'Oak Canyon Farms'),
('ocean_mist', 'Ocean Mist'),
('olivias_organics', 'Olivia''s Organics'),
('open_acres', 'Open Acres'),
('organic_girl', 'Organic Girl'),
('organic_llano', 'Organic Llano'),
('organic_marketside', 'Organic Marketside'),
('other_unknown', 'Other (unknown)'),
('pam_pak', 'Pam Pak'),
('pandol', 'Pandol'),
('pazazz', 'Pazazz'),
('pero', 'Pero'),
('petes_living_organic', 'Petes Living Organic'),
('pink_lady', 'Pink Lady'),
('pixie_pears', 'Pixie pears'),
('prairerth_farm', 'Prairerth Farm'),
('prima', 'Prima'),
('private_selection', 'Private Selection'),
('pure_flavor', 'Pure Flavor'),
('ranier', 'Ranier'),
('ratto_bros', 'Ratto Bros'),
('red_sun_farms', 'Red Sun Farms'),
('rivermaid', 'Rivermaid'),
('safeway', 'Safeway'),
('samsons', 'Samsons'),
('santa_sweets', 'Santa Sweets'),
('signature_brand', 'Signature Brand'),
('silver_canyon', 'Silver Canyon'),
('simple_truth', 'Simple Truth'),
('simply_nature', 'Simply Nature'),
('skagit_valley', 'Skagit Valley'),
('spiral_path_farm', 'Spiral Path Farm'),
('starr_ranch', 'Starr Ranch'),
('stemilt', 'Stemilt'),
('strohauer_farms', 'Strohauer Farms'),
('sugar_fresh_organics', 'Sugar Fresh Organics'),
('sun_disk', 'Sun Disk'),
('sunset', 'Sunset'),
('sunview', 'Sunview'),
('taylor_farms', 'Taylor Farms'),
('tomorows_organic', 'Tomorow''s Organic'),
('top_line_farms', 'Top line farms'),
('topline', 'Topline'),
('tuscarara_farms', 'Tuscarara Farms'),
('unlabeled_package', 'Unlabeled Package'),
('washington', 'Washington'),
('werita', 'Werita'),
('melissas', 'Melissas'),
('trader_joes', 'Trader Joes'),
('grown_true', 'Grown True'),
('aztlan', 'Aztlan'),
('rainier', 'Rainier'),
('hearts_of_romaine_lettuce', 'Hearts of Romaine Lettuce'),
('tasteful_selections', 'Tasteful Selections'),
('happy_living', 'Happy Living'),
('lakeside_organic_gardens', 'Lakeside Organic Gardens'),
('4_earth_farms', '4 Earth Farms'),
('sugar_bee', 'Sugar Bee'),
('earthbound_farm', 'Earthbound Farm'),
('farmers_promise', 'Farmers Promise'),
('wholesum_harvest', 'Wholesum Harvest'),
('bolthouse_farms', 'bolthouse_farms'),
('les_saludes_du_midi', 'Les Saludes Du Midi'),
('farmers_best', 'Farmers Best'),
('divine_flavor', 'Divine Flavor'),
('igl_farms', 'igl_farms'),
('bonipak', 'Bonipak'),
('naturipe_farms', 'Naturipe Farms'),
('valley_farms', 'Valley Farms');