-- This script inserts a comprehensive list of stores into the 'public.stores' table,
-- assigning a specific 'type' to each entry. The script is designed to be idempotent,
-- meaning it can be run multiple times without causing errors due to existing data.

INSERT INTO public.stores (id, name, label, type)
VALUES
  (gen_random_uuid(), '7_star_food_center', '7 Star Food Center', 'Grocery'),
  (gen_random_uuid(), 'acme', 'Acme', 'Grocery'),
  (gen_random_uuid(), 'albertsons', 'Albertsons', 'Grocery'),
  (gen_random_uuid(), 'aldi', 'Aldi', 'Grocery'),
  (gen_random_uuid(), 'alfalfas', 'Alfalfas', 'Health'),
  (gen_random_uuid(), 'andys_market', 'Andy''s Market', 'Grocery'),
  (gen_random_uuid(), 'arbor_farms_market', 'Arbor Farms Market', 'Health'),
  (gen_random_uuid(), 'basic_market', 'Basic Market', 'Grocery'),
  (gen_random_uuid(), 'beaumont_market', 'Beaumont Market', 'Grocery'),
  (gen_random_uuid(), 'big_y', 'Big Y', 'Grocery'),
  (gen_random_uuid(), 'blue_parkway_sunfresh', 'Blue Parkway Sunfresh', 'Grocery'),
  (gen_random_uuid(), 'bounty_and_soul', 'Bounty And Soul', 'Community'),
  (gen_random_uuid(), 'brito_supermarket', 'Brito Supermarket', 'Grocery'),
  (gen_random_uuid(), 'buschs_fresh_food_market', 'Busch''s Fresh Food Market', 'Grocery'),
  (gen_random_uuid(), 'carrs_safeway', 'Carrs/Safeway', 'Grocery'),
  (gen_random_uuid(), 'costco', 'Costco', 'Club'),
  (gen_random_uuid(), 'daves_market', 'Dave''s Market', 'Grocery'),
  (gen_random_uuid(), 'dill_pickle_food_coop', 'Dill Pickle Food Coop', 'Community'),
  (gen_random_uuid(), 'dons', 'Don''s', 'Grocery'),
  (gen_random_uuid(), 'earth_fair', 'Earth Fair', 'Health'),
  (gen_random_uuid(), 'everybodys', 'Everybodys', 'Grocery'),
  (gen_random_uuid(), 'fairway_market', 'Fairway Market', 'Grocery'),
  (gen_random_uuid(), 'fitzgeralds', 'Fitzgerald''s', 'Grocery'),
  (gen_random_uuid(), 'food_4_less', 'Food 4 less', 'Grocery'),
  (gen_random_uuid(), 'food_maxx', 'Food Maxx', 'Grocery'),
  (gen_random_uuid(), 'fred_meyer', 'Fred Meyer', 'Grocery'),
  (gen_random_uuid(), 'fresh_grocer', 'Fresh Grocer', 'Grocery'),
  (gen_random_uuid(), 'fresh_thyme', 'Fresh Thyme', 'Health'),
  (gen_random_uuid(), 'fruit_basket', 'Fruit Basket', 'Specialty'),
  (gen_random_uuid(), 'garden_fresh_marketplace', 'Garden Fresh Marketplace', 'Grocery'),
  (gen_random_uuid(), 'geisslers', 'Geisslers', 'Grocery'),
  (gen_random_uuid(), 'green_farm_market', 'Green Farm Market', 'Grocery'),
  (gen_random_uuid(), 'gregs_produce', 'Greg''s Produce', 'Farmers'),
  (gen_random_uuid(), 'grocery_basket', 'Grocery basket', 'Grocery'),
  (gen_random_uuid(), 'h_e_b', 'H-E-B', 'Grocery'),
  (gen_random_uuid(), 'haggen', 'Haggen', 'Grocery'),
  (gen_random_uuid(), 'hannaford', 'Hannaford', 'Grocery'),
  (gen_random_uuid(), 'hardings_market', 'Harding''s Market', 'Grocery'),
  (gen_random_uuid(), 'hawkins', 'Hawkins', 'Grocery'),
  (gen_random_uuid(), 'healthy_living', 'Healthy Living', 'Health'),
  (gen_random_uuid(), 'heinens', 'Heinens', 'Grocery'),
  (gen_random_uuid(), 'hy_vee', 'Hy-Vee', 'Grocery'),
  (gen_random_uuid(), 'imperfect_produce', 'Imperfect Produce', 'Specialty'),
  (gen_random_uuid(), 'imperial_fresh_market', 'Imperial Fresh Market', 'Grocery'),
  (gen_random_uuid(), 'jewel_supermarket', 'Jewel Supermarket', 'Grocery'),
  (gen_random_uuid(), 'jubilee', 'Jubilee', 'Grocery'),
  (gen_random_uuid(), 'kanes_market', 'Kanes Market', 'Grocery'),
  (gen_random_uuid(), 'king_cole_foods', 'King Cole Foods', 'Grocery'),
  (gen_random_uuid(), 'king_soopers', 'King Soopers', 'Grocery'),
  (gen_random_uuid(), 'kroger', 'Kroger', 'Grocery'),
  (gen_random_uuid(), 'la_fiesta_supermarket', 'La Fiesta Supermarket', 'Specialty'),
  (gen_random_uuid(), 'lazy_a_health_store', 'Lazy A Health Store', 'Health'),
  (gen_random_uuid(), 'lidl', 'Lidl', 'Grocery'),
  (gen_random_uuid(), 'luckys_market', 'Luckys Market', 'Grocery'),
  (gen_random_uuid(), 'marcs', 'Marcs', 'Grocery'),
  (gen_random_uuid(), 'meijer', 'Meijer', 'Grocery'),
  (gen_random_uuid(), 'mock_crest_grocery', 'Mock Crest Grocery', 'Grocery'),
  (gen_random_uuid(), 'morning_glory_natural_foods', 'Morning Glory Natural Foods', 'Health'),
  (gen_random_uuid(), 'natural_grocers', 'Natural Grocers', 'Health'),
  (gen_random_uuid(), 'pak_n_save', 'Pak n'' Save', 'Grocery'),
  (gen_random_uuid(), 'paradise_health_&_nutrition', 'Paradise Health & Nutrition', 'Health'),
  (gen_random_uuid(), 'peoples_food_co_op', 'Peoples Food Co-Op', 'Community'),
  (gen_random_uuid(), 'plum_market', 'Plum Market', 'Specialty'),
  (gen_random_uuid(), 'quick_faso_market', 'Quick Faso Market', 'Grocery'),
  (gen_random_uuid(), 'ralphs_supermarket', 'Ralphs Supermarket', 'Grocery'),
  (gen_random_uuid(), 'royal_food_supermarket', 'Royal Food SuperMarket', 'Grocery'),
  (gen_random_uuid(), 'saars_super_saver_foods', 'Saars Super Saver Foods', 'Grocery'),
  (gen_random_uuid(), 'sacramento_co-op', 'Sacramento Co-Op', 'Community'),
  (gen_random_uuid(), 'safeway', 'Safeway', 'Grocery'),
  (gen_random_uuid(), 'save_a_lot', 'Save a Lot', 'Grocery'),
  (gen_random_uuid(), 'save_line_market', 'Save Line Market', 'Grocery'),
  (gen_random_uuid(), 'shoprite', 'Shoprite', 'Grocery'),
  (gen_random_uuid(), 'south_loop_market', 'South loop market', 'Grocery'),
  (gen_random_uuid(), 'sprouts', 'Sprouts', 'Health'),
  (gen_random_uuid(), 'stop___shop', 'Stop & Shop', 'Grocery'),
  (gen_random_uuid(), 'sun_plum_market', 'Sun Plum Market', 'Grocery'),
  (gen_random_uuid(), 'super_giant_supermarket', 'Super Giant Supermarket', 'Grocery'),
  (gen_random_uuid(), 'target', 'Target', 'Grocery'),
  (gen_random_uuid(), 'taylors_market', 'Taylors Market', 'Specialty'),
  (gen_random_uuid(), 'tesco', 'Tesco', 'Grocery'),
  (gen_random_uuid(), 'the_dutchman', 'The Dutchman', 'Grocery'),
  (gen_random_uuid(), 'the_golden_dome_market', 'The Golden Dome Market', 'Grocery'),
  (gen_random_uuid(), 'the_greengrocer', 'The Greengrocer', 'Specialty'),
  (gen_random_uuid(), 'tonys_fresh_market', 'Tonys Fresh Market', 'Grocery'),
  (gen_random_uuid(), 'trader_joes', 'Trader Joes', 'Specialty'),
  (gen_random_uuid(), 'trigs', 'Trigs', 'Grocery'),
  (gen_random_uuid(), 'trouts_jubilee', 'Trouts Jubilee', 'Grocery'),
  (gen_random_uuid(), 'uwajimaya', 'Uwajimaya', 'Specialty'),
  (gen_random_uuid(), 'waitrose', 'Waitrose', 'Grocery'),
  (gen_random_uuid(), 'walmart', 'Walmart', 'Grocery'),
  (gen_random_uuid(), 'wegmans', 'Wegmans', 'Grocery'),
  (gen_random_uuid(), 'whole_foods', 'Whole Foods', 'Health'),
  (gen_random_uuid(), 'woodmans', 'Woodmans', 'Grocery')
ON CONFLICT (name) DO NOTHING;
