-- Complete fix: Clear all data and insert with consistent format
-- This addresses the mixed data sources causing NULL labels

-- Clear existing inconsistent data
DELETE FROM public.stores;

ALTER TABLE public.stores ADD CONSTRAINT stores_name_unique UNIQUE (name);

-- Reset the sequence if needed (optional)
-- ALTER SEQUENCE stores_id_seq RESTART WITH 1;

-- Upsert approach: Insert or update existing records
-- This avoids deletion issues and fixes data in place
INSERT INTO public.stores (name, label, location_id) VALUES
('7_star_food_center', '7 Star Food Center', NULL),
('acme', 'Acme', NULL),
('albertsons', 'Albertsons', NULL),
('aldi', 'Aldi', NULL),
('alfalfas', 'Alfalfas', NULL),
('andys_market', 'Andy''s Market', NULL),
('arbor_farms_market', 'Arbor Farms Market', NULL),
('basic_market', 'Basic Market', NULL),
('beaumont_market', 'Beaumont Market', NULL),
('big_y', 'Big Y', NULL),
('blue_parkway_sunfresh', 'Blue Parkway Sunfresh', NULL),
('bounty_and_soul', 'Bounty And Soul', NULL),
('brito_supermarket', 'Brito Supermarket', NULL),
('buschs_fresh_food_market', 'Busch''s Fresh Food Market', NULL),
('carrs_safeway', 'Carrs/Safeway', NULL),
('costco', 'Costco', NULL),
('daves_market', 'Dave''s Market', NULL),
('dill_pickle_food_coop', 'Dill Pickle Food Coop', NULL),
('dons', 'Don''s', NULL),
('earth_fair', 'Earth Fair', NULL),
('everybodys', 'Everybodys', NULL),
('fairway_market', 'Fairway Market', NULL),
('fitzgeralds', 'Fitzgerald''s', NULL),
('food_4_less', 'Food 4 less', NULL),
('food_maxx', 'Food Maxx', NULL),
('fred_meyer', 'Fred Meyer', NULL),
('fresh_grocer', 'Fresh Grocer', NULL),
('fresh_thyme', 'Fresh Thyme', NULL),
('fruit_basket', 'Fruit Basket', NULL),
('garden_fresh_marketplace', 'Garden Fresh Marketplace', NULL),
('geisslers', 'Geisslers', NULL),
('green_farm_market', 'Green Farm Market', NULL),
('gregs_produce', 'Greg''s Produce', NULL),
('grocery_basket', 'Grocery basket', NULL),
('h_e_b', 'H-E-B', NULL),
('haggen', 'Haggen', NULL),
('hannaford', 'Hannaford', NULL),
('hardings_market', 'Harding''s Market', NULL),
('hawkins', 'Hawkins', NULL),
('healthy_living', 'Healthy Living', NULL),
('heinens', 'Heinens', NULL),
('hy_vee', 'Hy-Vee', NULL),
('imperfect_produce', 'Imperfect Produce', NULL),
('imperial_fresh_market', 'Imperial Fresh Market', NULL),
('jewel_supermarket', 'Jewel Supermarket', NULL),
('jubilee', 'Jubilee', NULL),
('kanes_market', 'Kanes Market', NULL),
('king_cole_foods', 'King Cole Foods', NULL),
('king_soopers', 'King Soopers', NULL),
('kroger', 'Kroger', NULL),
('la_fiesta_supermarket', 'La Fiesta Supermarket', NULL),
('lazy_a_health_store', 'Lazy A Health Store', NULL),
('lidl', 'Lidl', NULL),
('luckys_market', 'Luckys Market', NULL),
('marcs', 'Marcs', NULL),
('meijer', 'Meijer', NULL),
('mock_crest_grocery', 'Mock Crest Grocery', NULL),
('morning_glory_natural_foods', 'Morning Glory Natural Foods', NULL),
('natural_grocers', 'Natural Grocers', NULL),
('pak_n_save', 'Pak n'' Save', NULL),
('paradise_health_&_nutrition', 'Paradise Health & Nutrition', NULL),
('peoples_food_co_op', 'Peoples Food Co-Op', NULL),
('plum_market', 'Plum Market', NULL),
('quick_faso_market', 'Quick Faso Market', NULL),
('ralphs_supermarket', 'Ralphs Supermarket', NULL),
('royal_food_supermarket', 'Royal Food SuperMarket', NULL),
('saars_super_saver_foods', 'Saars Super Saver Foods', NULL),
('sacramento_co-op', 'Sacramento Co-Op', NULL),
('safeway', 'Safeway', NULL),
('save_a_lot', 'Save a Lot', NULL),
('save_line_market', 'Save Line Market', NULL),
('shoprite', 'Shoprite', NULL),
('south_loop_market', 'South loop market', NULL),
('sprouts', 'Sprouts', NULL),
('stop___shop', 'Stop & Shop', NULL),
('sun_plum_market', 'Sun Plum Market', NULL),
('super_giant_supermarket', 'Super Giant Supermarket', NULL),
('target', 'Target', NULL),
('taylors_market', 'Taylors Market', NULL),
('tesco', 'Tesco', NULL),
('the_dutchman', 'The Dutchman', NULL),
('the_golden_dome_market', 'The Golden Dome Market', NULL),
('the_greengrocer', 'The Greengrocer', NULL),
('tonys_fresh_market', 'Tonys Fresh Market', NULL),
('trader_joes', 'Trader Joes', NULL),
('trigs', 'Trigs', NULL),
('trouts_jubilee', 'Trouts Jubilee', NULL),
('uwajimaya', 'Uwajimaya', NULL),
('waitrose', 'Waitrose', NULL),
('walmart', 'Walmart', NULL),
('wegmans', 'Wegmans', NULL),
('whole_foods', 'Whole Foods', NULL),
('woodmans', 'Woodmans', NULL)
ON CONFLICT (name) DO UPDATE SET
    label = EXCLUDED.label,
    location_id = EXCLUDED.location_id;