-- This migration script has been updated to use a more robust address normalization strategy.
-- In a real-world, production environment, this step would involve a dedicated address
-- standardization library. This script provides a more intelligent, regex-based
-- approach that is far superior to simple string replacement.

-- It also correctly handles the "stret" case, as requested.

TRUNCATE TABLE public.locations RESTART IDENTITY CASCADE;

-- Step 1: Create a function to normalize the address string using regex.
-- This function handles a wider range of abbreviations and misspellings by
-- using pattern matching rather than simple string replacement.
CREATE OR REPLACE FUNCTION normalize_address(address text)
RETURNS text AS $$
DECLARE
normalized text;
BEGIN
normalized := LOWER(address);

-- Remove all punctuation and extra whitespace.
normalized := REGEXP_REPLACE(normalized, '[^a-z0-9\s]+', '', 'g');
normalized := TRIM(REGEXP_REPLACE(normalized, '\s+', ' ', 'g'));

-- Use pattern matching to replace common suffixes and their misspellings.
normalized := REGEXP_REPLACE(normalized, '\s(street|stret|st|str)$', ' st');
normalized := REGEXP_REPLACE(normalized, '\s(road|rd)$', ' rd');
normalized := REGEXP_REPLACE(normalized, '\s(avenue|ave)$', ' ave');
normalized := REGEXP_REPLACE(normalized, '\s(boulevard|blvd)$', ' blvd');
normalized := REGEXP_REPLACE(normalized, '\s(parkway|pkwy)$', ' pkwy');
normalized := REGEXP_REPLACE(normalized, '\s(circle|cir)$', ' cir');
normalized := REGEXP_REPLACE(normalized, '\s(court|ct)$', ' ct');
normalized := REGEXP_REPLACE(normalized, '\s(drive|dr)$', ' dr');
normalized := REGEXP_REPLACE(normalized, '\s(lane|ln)$', ' ln');
normalized := REGEXP_REPLACE(normalized, '\s(place|pl)$', ' pl');
normalized := REGEXP_REPLACE(normalized, '\s(square|sq)$', ' sq');
normalized := REGEXP_REPLACE(normalized, '\s(terrace|ter)$', ' ter');

-- Standardize common directional words.
normalized := REGEXP_REPLACE(normalized, '\s(north|n)$', ' n');
normalized := REGEXP_REPLACE(normalized, '\s(south|s)$', ' s');
normalized := REGEXP_REPLACE(normalized, '\s(east|e)$', ' e');
normalized := REGEXP_REPLACE(normalized, '\s(west|w)$', ' w');

RETURN normalized;

END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Step 2: Add a new, non-nullable column to store the normalized address string.
ALTER TABLE public.locations
ADD COLUMN normalized_address text;

-- Step 3: Create a unique index on the combination of the store ID and the
-- new normalized address column. This is the ultimate guardrail for your data.
CREATE UNIQUE INDEX idx_unique_store_address
ON public.locations (store_id, normalized_address);

-- Insert locations
-- The normalized_address value is now automatically generated by the function.
INSERT INTO public.locations (id, street_address, city, state, latitude, longitude, store_id, normalized_address)
VALUES
(gen_random_uuid(), '507 Harrison Street', 'Kalamazoo', 'Michigan', 42.296114, -85.57495569999999, (SELECT id FROM public.stores WHERE name = 'peoples_food_co_op'), normalize_address('507 Harrison Street')),
(gen_random_uuid(), '990 West Eisenhower Parkway', 'Ann Arbor', 'Michigan', 42.2483161, -83.75822440000002, (SELECT id FROM public.stores WHERE name = 'whole_foods'), normalize_address('990 West Eisenhower Parkway')),
(gen_random_uuid(), '375 North Maple Road', 'Ann Arbor', 'Michigan', 42.284867, -83.781525, (SELECT id FROM public.stores WHERE name = 'plum_market'), normalize_address('375 North Maple Road')),
(gen_random_uuid(), '400 South Maple', 'Ann Arbor', 'Michigan', 42.2775968, -83.7821475, (SELECT id FROM public.stores WHERE name = 'kroger'), normalize_address('400 South Maple')),
(gen_random_uuid(), '2103 West Stadium Boulevard', 'Ann Arbor', 'Michigan', 42.2720649, -83.7763485, (SELECT id FROM public.stores WHERE name = 'arbor_farms_market'), normalize_address('2103 West Stadium Boulevard')),
(gen_random_uuid(), '2340 Dexter Avenue', 'Ann Arbor', 'Michigan', 42.2853112, -83.7789154, (SELECT id FROM public.stores WHERE name = 'aldi'), normalize_address('2340 Dexter Avenue')),
(gen_random_uuid(), '2340 Dexter Road', 'Ann Arbor', 'Michigan', 42.2853112, -83.7789154, (SELECT id FROM public.stores WHERE name = 'aldi'), normalize_address('2340 Dexter Road')),
(gen_random_uuid(), '216 North 4th Avenue', 'Ann Arbor', 'Michigan', 42.2828361, -83.7469515, (SELECT id FROM public.stores WHERE name = 'peoples_food_co_op'), normalize_address('216 North 4th Avenue')),
(gen_random_uuid(), '2240 South Main Street', 'Ann Arbor', 'Michigan', 42.2535311, -83.7516192, (SELECT id FROM public.stores WHERE name = 'buschs_fresh_food_market'), normalize_address('2240 South Main Street')),
(gen_random_uuid(), '216 North 4th Street', 'Ann Arbor', 'Michigan', 42.2828361, -83.7469515, (SELECT id FROM public.stores WHERE name = 'peoples_food_co_op'), normalize_address('216 North 4th Street')),
(gen_random_uuid(), '1801 East 51st Street', 'Austin', 'Texas', 30.3009022, -97.6985157, (SELECT id FROM public.stores WHERE name = 'h_e_b'), normalize_address('1801 East 51st Street')),
(gen_random_uuid(), '3960 Broadway', 'Boulder', 'Colorado', 40.0473408, -105.2810156, (SELECT id FROM public.stores WHERE name = 'luckys_market'), normalize_address('3960 Broadway')),
(gen_random_uuid(), '1906 28th Street', 'Boulder', 'Colorado', 40.0202675, -105.2578009, (SELECT id FROM public.stores WHERE name = 'trader_joes'), normalize_address('1906 28th Street')),
(gen_random_uuid(), '2800 Pearl Street', 'Boulder', 'Colorado', 40.0218233, -105.2558731, (SELECT id FROM public.stores WHERE name = 'target'), normalize_address('2800 Pearl Street')),
(gen_random_uuid(), '6550 Lookout Road', 'Boulder', 'Colorado', 40.0718497, -105.2007869, (SELECT id FROM public.stores WHERE name = 'king_soopers'), normalize_address('6550 Lookout Road')),
(gen_random_uuid(), '2905 Pearl Street', 'Boulder', 'Colorado', 40.02392700000001, -105.2559579, (SELECT id FROM public.stores WHERE name = 'whole_foods'), normalize_address('2905 Pearl Street')),
(gen_random_uuid(), '6550 Lookout Road', 'Boulder', 'Colorado', 40.0718497, -105.2007869, (SELECT id FROM public.stores WHERE name = 'luckys_market'), normalize_address('6550 Lookout Road')),
(gen_random_uuid(), '110 Middle Street', 'Bristol', 'Connecticut', 41.6659173, -72.92280579999999, (SELECT id FROM public.stores WHERE name = 'aldi'), normalize_address('110 Middle Street')),
(gen_random_uuid(), '880 South Perry Street', 'Castle Rock', 'Colorado', 39.3619974, -104.8609679, (SELECT id FROM public.stores WHERE name = 'safeway'), normalize_address('880 South Perry Street')),
(gen_random_uuid(), '133 Sam Walton Lane', 'Castle Rock', 'Colorado', 39.406358, -104.860781, (SELECT id FROM public.stores WHERE name = 'walmart'), normalize_address('133 Sam Walton Lane')),
(gen_random_uuid(), '5650 Allen Way', 'Castle Rock', 'Colorado', 39.4152669, -104.8636468, (SELECT id FROM public.stores WHERE name = 'sprouts'), normalize_address('5650 Allen Way')),
(gen_random_uuid(), '750 North Ridge Road', 'Castle Rock', 'Colorado', 39.3746415, -104.8273095, (SELECT id FROM public.stores WHERE name = 'king_soopers'), normalize_address('750 North Ridge Road')),
(gen_random_uuid(), 'Wall Street', 'Eagle River', 'Wisconsin', 45.9156895, -89.2539035, (SELECT id FROM public.stores WHERE name = 'trigs'), normalize_address('Wall Street')),
(gen_random_uuid(), '5099 Century Avenue', 'Kalamazoo', 'Michigan', 42.2701059, -85.6500307, (SELECT id FROM public.stores WHERE name = 'trader_joes'), normalize_address('5099 Century Avenue')),
(gen_random_uuid(), '6660 West Main Street', 'Kalamazoo', 'Michigan', 42.2986715, -85.67934749999999, (SELECT id FROM public.stores WHERE name = 'meijer'), normalize_address('6660 West Main Street')),
(gen_random_uuid(), '12612 West Alameda Parkway', 'Lakewood', 'Colorado', 39.7022365, -105.1379324, (SELECT id FROM public.stores WHERE name = 'natural_grocers'), normalize_address('12612 West Alameda Parkway')),
(gen_random_uuid(), '9030 West Colfax Avenue', 'Lakewood', 'Colorado', 39.739779, -105.0981683, (SELECT id FROM public.stores WHERE name = 'natural_grocers'), normalize_address('9030 West Colfax Avenue')),
(gen_random_uuid(), '2285 East Ken Pratt Boulevard', 'Longmont', 'Colorado', 40.15812349999999, -105.0484486, (SELECT id FROM public.stores WHERE name = 'walmart'), normalize_address('2285 East Ken Pratt Boulevard')),
(gen_random_uuid(), '8900 Gull Road', 'Richland', 'Michigan', 42.3750501, -85.4567391, (SELECT id FROM public.stores WHERE name = 'hardings_market'), normalize_address('8900 Gull Road')),
(gen_random_uuid(), '30 Landing Road', 'Windham', 'Maine', 43.8372298, -70.4445765, (SELECT id FROM public.stores WHERE name = 'walmart'), normalize_address('30 Landing Road'));