// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbkzczcqlorsewoofwqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6India3pjemNxbG9yc2V3b29md3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTkyMDYsImV4cCI6MjA2NzczNTIwNn0.2SjN-hegbgQviXkjNULudnDuFJtNnePJhlNHGcr4Cfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});