name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history needed to avoid shallow clone issues

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "sync@github-actions.local"

      - name: Add GitLab remote
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_TOKEN@${GITLAB_REPO#https://}

      - name: Fetch GitLab main branch
        run: |
          git fetch gitlab main

      - name: Merge GitLab main branch (safe merge)
        run: |
          git merge --allow-unrelated-histories --no-edit gitlab/main || true

      - name: Push changes to GitLab
        run: |
          git push gitlab HEAD:main